.PHONY:
	clean
	all

array_queue:
	g++ -Wall -DUSE_ARRAY_QUEUE main.cpp -o arrayQueue

linked_queue:
	g++ -Wall -DUSE_LINKED_QUEUE main.cpp -o linkedQueue

clean:
	rm -rf arrayQueue
	rm -rf linkedQueue