.PHONY:
	clean
	all

array_stack:
	g++ -Wall -DUSE_ARRAY_STACK main.cpp -o arrayStack

linked_stack:
	g++ -Wall -DUSE_LINKED_STACK main.cpp -o linkedStack

clean:
	rm -rf arrayStack
	rm -rf linkedStack