.PHONY:
	clean
	all

insertion_sort:
	g++ -DUSE_INSERTION_SORT -o insertion_sort main.cpp

bubble_sort:
	g++ -DUSE_BUBBLE_SORT -o bubble_sort main.cpp

clean:
	rm -rf insertion_sort
	rm -rf bubble_sort